[System.Serializable]
public sealed class CharacterManagerZSerializer : ZSerializer.Internal.ZSerializer
{
    public CharacterSheet characterSheet;
    public System.Single healthCurrent;
    public System.Single staminaCurrent;
    public System.Single healthTotal;
    public System.Single staminaTotal;
    public System.Int32 armourDefenceTotal;
    public System.Int32 bonusDefence;
    public System.Int32 bonusDamage;
    public System.Int32 effectResistChance;
    public Item equippedWeapon;
    public ShieldItem equippedShield;
    public EquipmentItem equippedArmour;
    public EquipmentItem equippedCape;
    public EquipmentItem equippedFeet;
    public EquipmentItem equippedGreaves;
    public EquipmentItem equippedHands;
    public EquipmentItem equippedHelmet;
    public EquipmentItem equippedPants;
    public EquipmentItem equippedShirt;
    public System.Collections.Generic.List<Item> currentInventory;
    public System.Collections.Generic.List<Spell> currentSpells;
    public System.Collections.Generic.List<Skill> currentSkills;
    public DialogueGraph dialogueGraphInstance;
    public System.Collections.Generic.List<DialogueTopicsNode.Topic> alreadyRunDialogueTopics;
    public System.Collections.Generic.List<Effect> currentEffects;
    public System.Collections.Generic.List<Effect> endedEffects;
    public System.Boolean isHidden;
    public CharacterState characterState;
    public System.Boolean hasAdvantage;
    public System.Boolean hasDisadvantage;
    public System.Boolean inCombat;
    public System.Boolean isCrouching;
    public System.Collections.Generic.List<CharacterManager> inCombatWith;
    public System.Int32 berzerkerDamageBonus;
    public System.Int32 oneManArmyDefenceBonus;
    public System.Collections.Generic.List<CharacterManager> inDetectionRange;
    public Effect _disablingShotEffect;
    public System.Int32 groupID;
    public System.Boolean autoSync;

    public CharacterManagerZSerializer(string ZUID, string GOZUID) : base(ZUID, GOZUID)
    {       var instance = ZSerializer.ZSerialize.idMap[ZSerializer.ZSerialize.CurrentGroupID][ZUID];
         characterSheet = (CharacterSheet)typeof(CharacterManager).GetField("characterSheet").GetValue(instance);
         healthCurrent = (System.Single)typeof(CharacterManager).GetField("healthCurrent").GetValue(instance);
         staminaCurrent = (System.Single)typeof(CharacterManager).GetField("staminaCurrent").GetValue(instance);
         healthTotal = (System.Single)typeof(CharacterManager).GetField("healthTotal").GetValue(instance);
         staminaTotal = (System.Single)typeof(CharacterManager).GetField("staminaTotal").GetValue(instance);
         armourDefenceTotal = (System.Int32)typeof(CharacterManager).GetField("armourDefenceTotal").GetValue(instance);
         bonusDefence = (System.Int32)typeof(CharacterManager).GetField("bonusDefence").GetValue(instance);
         bonusDamage = (System.Int32)typeof(CharacterManager).GetField("bonusDamage").GetValue(instance);
         effectResistChance = (System.Int32)typeof(CharacterManager).GetField("effectResistChance").GetValue(instance);
         equippedWeapon = (Item)typeof(CharacterManager).GetField("equippedWeapon").GetValue(instance);
         equippedShield = (ShieldItem)typeof(CharacterManager).GetField("equippedShield").GetValue(instance);
         equippedArmour = (EquipmentItem)typeof(CharacterManager).GetField("equippedArmour").GetValue(instance);
         equippedCape = (EquipmentItem)typeof(CharacterManager).GetField("equippedCape").GetValue(instance);
         equippedFeet = (EquipmentItem)typeof(CharacterManager).GetField("equippedFeet").GetValue(instance);
         equippedGreaves = (EquipmentItem)typeof(CharacterManager).GetField("equippedGreaves").GetValue(instance);
         equippedHands = (EquipmentItem)typeof(CharacterManager).GetField("equippedHands").GetValue(instance);
         equippedHelmet = (EquipmentItem)typeof(CharacterManager).GetField("equippedHelmet").GetValue(instance);
         equippedPants = (EquipmentItem)typeof(CharacterManager).GetField("equippedPants").GetValue(instance);
         equippedShirt = (EquipmentItem)typeof(CharacterManager).GetField("equippedShirt").GetValue(instance);
         currentInventory = (System.Collections.Generic.List<Item>)typeof(CharacterManager).GetField("currentInventory").GetValue(instance);
         currentSpells = (System.Collections.Generic.List<Spell>)typeof(CharacterManager).GetField("currentSpells").GetValue(instance);
         currentSkills = (System.Collections.Generic.List<Skill>)typeof(CharacterManager).GetField("currentSkills").GetValue(instance);
         dialogueGraphInstance = (DialogueGraph)typeof(CharacterManager).GetField("dialogueGraphInstance").GetValue(instance);
         alreadyRunDialogueTopics = (System.Collections.Generic.List<DialogueTopicsNode.Topic>)typeof(CharacterManager).GetField("alreadyRunDialogueTopics").GetValue(instance);
         currentEffects = (System.Collections.Generic.List<Effect>)typeof(CharacterManager).GetField("currentEffects").GetValue(instance);
         endedEffects = (System.Collections.Generic.List<Effect>)typeof(CharacterManager).GetField("endedEffects").GetValue(instance);
         isHidden = (System.Boolean)typeof(CharacterManager).GetField("isHidden").GetValue(instance);
         characterState = (CharacterState)typeof(CharacterManager).GetField("characterState").GetValue(instance);
         hasAdvantage = (System.Boolean)typeof(CharacterManager).GetField("hasAdvantage").GetValue(instance);
         hasDisadvantage = (System.Boolean)typeof(CharacterManager).GetField("hasDisadvantage").GetValue(instance);
         inCombat = (System.Boolean)typeof(CharacterManager).GetField("inCombat").GetValue(instance);
         isCrouching = (System.Boolean)typeof(CharacterManager).GetField("isCrouching").GetValue(instance);
         inCombatWith = (System.Collections.Generic.List<CharacterManager>)typeof(CharacterManager).GetField("inCombatWith").GetValue(instance);
         berzerkerDamageBonus = (System.Int32)typeof(CharacterManager).GetField("berzerkerDamageBonus").GetValue(instance);
         oneManArmyDefenceBonus = (System.Int32)typeof(CharacterManager).GetField("oneManArmyDefenceBonus").GetValue(instance);
         inDetectionRange = (System.Collections.Generic.List<CharacterManager>)typeof(CharacterManager).GetField("inDetectionRange").GetValue(instance);
         _disablingShotEffect = (Effect)typeof(CharacterManager).GetField("_disablingShotEffect").GetValue(instance);
         groupID = (System.Int32)typeof(ZSerializer.PersistentMonoBehaviour).GetField("groupID", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic).GetValue(instance);
         autoSync = (System.Boolean)typeof(ZSerializer.PersistentMonoBehaviour).GetField("autoSync", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic).GetValue(instance);
    }

    public override void RestoreValues(UnityEngine.Component component)
    {
         typeof(CharacterManager).GetField("characterSheet").SetValue(component, characterSheet);
         typeof(CharacterManager).GetField("healthCurrent").SetValue(component, healthCurrent);
         typeof(CharacterManager).GetField("staminaCurrent").SetValue(component, staminaCurrent);
         typeof(CharacterManager).GetField("healthTotal").SetValue(component, healthTotal);
         typeof(CharacterManager).GetField("staminaTotal").SetValue(component, staminaTotal);
         typeof(CharacterManager).GetField("armourDefenceTotal").SetValue(component, armourDefenceTotal);
         typeof(CharacterManager).GetField("bonusDefence").SetValue(component, bonusDefence);
         typeof(CharacterManager).GetField("bonusDamage").SetValue(component, bonusDamage);
         typeof(CharacterManager).GetField("effectResistChance").SetValue(component, effectResistChance);
         typeof(CharacterManager).GetField("equippedWeapon").SetValue(component, equippedWeapon);
         typeof(CharacterManager).GetField("equippedShield").SetValue(component, equippedShield);
         typeof(CharacterManager).GetField("equippedArmour").SetValue(component, equippedArmour);
         typeof(CharacterManager).GetField("equippedCape").SetValue(component, equippedCape);
         typeof(CharacterManager).GetField("equippedFeet").SetValue(component, equippedFeet);
         typeof(CharacterManager).GetField("equippedGreaves").SetValue(component, equippedGreaves);
         typeof(CharacterManager).GetField("equippedHands").SetValue(component, equippedHands);
         typeof(CharacterManager).GetField("equippedHelmet").SetValue(component, equippedHelmet);
         typeof(CharacterManager).GetField("equippedPants").SetValue(component, equippedPants);
         typeof(CharacterManager).GetField("equippedShirt").SetValue(component, equippedShirt);
         typeof(CharacterManager).GetField("currentInventory").SetValue(component, currentInventory);
         typeof(CharacterManager).GetField("currentSpells").SetValue(component, currentSpells);
         typeof(CharacterManager).GetField("currentSkills").SetValue(component, currentSkills);
         typeof(CharacterManager).GetField("dialogueGraphInstance").SetValue(component, dialogueGraphInstance);
         typeof(CharacterManager).GetField("alreadyRunDialogueTopics").SetValue(component, alreadyRunDialogueTopics);
         typeof(CharacterManager).GetField("currentEffects").SetValue(component, currentEffects);
         typeof(CharacterManager).GetField("endedEffects").SetValue(component, endedEffects);
         typeof(CharacterManager).GetField("isHidden").SetValue(component, isHidden);
         typeof(CharacterManager).GetField("characterState").SetValue(component, characterState);
         typeof(CharacterManager).GetField("hasAdvantage").SetValue(component, hasAdvantage);
         typeof(CharacterManager).GetField("hasDisadvantage").SetValue(component, hasDisadvantage);
         typeof(CharacterManager).GetField("inCombat").SetValue(component, inCombat);
         typeof(CharacterManager).GetField("isCrouching").SetValue(component, isCrouching);
         typeof(CharacterManager).GetField("inCombatWith").SetValue(component, inCombatWith);
         typeof(CharacterManager).GetField("berzerkerDamageBonus").SetValue(component, berzerkerDamageBonus);
         typeof(CharacterManager).GetField("oneManArmyDefenceBonus").SetValue(component, oneManArmyDefenceBonus);
         typeof(CharacterManager).GetField("inDetectionRange").SetValue(component, inDetectionRange);
         typeof(CharacterManager).GetField("_disablingShotEffect").SetValue(component, _disablingShotEffect);
         typeof(ZSerializer.PersistentMonoBehaviour).GetField("groupID", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic).SetValue(component, groupID);
         typeof(ZSerializer.PersistentMonoBehaviour).GetField("autoSync", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic).SetValue(component, autoSync);
    }
}